// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package core

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/tos-network/gtos/common"
	"github.com/tos-network/gtos/common/hexutil"
	"github.com/tos-network/gtos/common/math"
)

var _ = (*genesisAccountMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (g GenesisAccount) MarshalJSON() ([]byte, error) {
	type GenesisAccount struct {
		Code          hexutil.Bytes               `json:"code,omitempty"`
		Storage       map[storageJSON]storageJSON `json:"storage,omitempty"`
		Balance       *math.HexOrDecimal256       `json:"balance" gencodec:"required"`
		Nonce         math.HexOrDecimal64         `json:"nonce,omitempty"`
		PrivateKey    hexutil.Bytes               `json:"secretKey,omitempty"`
		SignerType    string                      `json:"signerType,omitempty"`
		SignerValue   string                      `json:"signerValue,omitempty"`
		UNOCommitment hexutil.Bytes               `json:"uno_ct_commitment,omitempty"`
		UNOHandle     hexutil.Bytes               `json:"uno_ct_handle,omitempty"`
		UNOVersion    math.HexOrDecimal64         `json:"uno_version,omitempty"`
	}
	var enc GenesisAccount
	enc.Code = g.Code
	if g.Storage != nil {
		enc.Storage = make(map[storageJSON]storageJSON, len(g.Storage))
		for k, v := range g.Storage {
			enc.Storage[storageJSON(k)] = storageJSON(v)
		}
	}
	enc.Balance = (*math.HexOrDecimal256)(g.Balance)
	enc.Nonce = math.HexOrDecimal64(g.Nonce)
	enc.PrivateKey = g.PrivateKey
	enc.SignerType = g.SignerType
	enc.SignerValue = g.SignerValue
	enc.UNOCommitment = g.UNOCommitment
	enc.UNOHandle = g.UNOHandle
	enc.UNOVersion = math.HexOrDecimal64(g.UNOVersion)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *GenesisAccount) UnmarshalJSON(input []byte) error {
	type GenesisAccount struct {
		Code          *hexutil.Bytes              `json:"code,omitempty"`
		Storage       map[storageJSON]storageJSON `json:"storage,omitempty"`
		Balance       *math.HexOrDecimal256       `json:"balance" gencodec:"required"`
		Nonce         *math.HexOrDecimal64        `json:"nonce,omitempty"`
		PrivateKey    *hexutil.Bytes              `json:"secretKey,omitempty"`
		SignerType    *string                     `json:"signerType,omitempty"`
		SignerValue   *string                     `json:"signerValue,omitempty"`
		UNOCommitment *hexutil.Bytes              `json:"uno_ct_commitment,omitempty"`
		UNOHandle     *hexutil.Bytes              `json:"uno_ct_handle,omitempty"`
		UNOVersion    *math.HexOrDecimal64        `json:"uno_version,omitempty"`
	}
	var dec GenesisAccount
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Code != nil {
		g.Code = *dec.Code
	}
	if dec.Storage != nil {
		g.Storage = make(map[common.Hash]common.Hash, len(dec.Storage))
		for k, v := range dec.Storage {
			g.Storage[common.Hash(k)] = common.Hash(v)
		}
	}
	if dec.Balance == nil {
		return errors.New("missing required field 'balance' for GenesisAccount")
	}
	g.Balance = (*big.Int)(dec.Balance)
	if dec.Nonce != nil {
		g.Nonce = uint64(*dec.Nonce)
	}
	if dec.PrivateKey != nil {
		g.PrivateKey = *dec.PrivateKey
	}
	if dec.SignerType != nil {
		g.SignerType = *dec.SignerType
	}
	if dec.SignerValue != nil {
		g.SignerValue = *dec.SignerValue
	}
	if dec.UNOCommitment != nil {
		g.UNOCommitment = *dec.UNOCommitment
	}
	if dec.UNOHandle != nil {
		g.UNOHandle = *dec.UNOHandle
	}
	if dec.UNOVersion != nil {
		g.UNOVersion = uint64(*dec.UNOVersion)
	}
	return nil
}
